### ISSUE TITLE
Add a way for users to create new locations

### ISSUE THREAD

**Issue by lkaratun** [chingu-voyage7/Bears-Team-09#80]
During event creation, if the entered City and Country doesn't exist in DB, allow user to create a new location. Both front and back end validation will be required.

**Comment by trolleksii** [comment]
Two approaches come to my mind:
1. Interactive typing. Each time user types additional letter frontend polls backend for such place, and displays available options. The more you type - the narrower the list. If there is no items - it displays button `Add place`. This approach is somewhat less prone to creating duplicates with the only difference in letter capitalization or typos.
2. Don't do any real time polling. Make place selector as a couple of dropdown lists, and put 'Add place' button somewhere around, that will draw kind of 'popup window' with input boxes. Due to the fact that now Country and City is in the same table and stored there as couple with uniqueness constraint.

I've seen first one more often, sometimes with cool features as some sort of relevance search.

**Comment by trolleksii** [comment]
In terms of validation, now backend checks for duplicates on POST request and will return an error.
The only problem is there is no 'normalization' of user input - 'Toronto, Canada' and 'TORONTO canada' is two different places. I guess that would make sense to implement it in the backend, making sure that capitalization is uniform. But there can be pitfalls as well, especially in compound names, like "Rio de Janeiro".

**Comment by vaidotasp** [comment]
> In terms of validation, now backend checks for duplicates on POST request and will return an error.
> The only problem is there is no 'normalization' of user input - 'Toronto, Canada' and 'TORONTO canada' is two different places. I guess that would make sense to implement it in the backend, making sure that capitalization is uniform. But there can be pitfalls as well, especially in compound names, like "Rio de Janeiro".

We could normalize data on frontend before sending it over? `String.toLowerCase()` ?

**Comment by vaidotasp** [comment]
Question for the group. Because of how similar this behavior is to Activity picker on a form, should it essentially be the same as place picker?

Meaning: user start typing activity and frontend pulls the list out of backend to display, if user is not able to find the activity they had in mind, they can create a new one right there in the input field and proceed?

@trolleksii @lkaratun

**Comment by lkaratun** [comment]
I think you should totally reuse the picker component for these 2 cases @vaidotasp

**Comment by vaidotasp** [comment]
Closing as it is implemented
